### ISSUE TITLE
Document error in Optimization_4x4_10

### ISSUE THREAD

**Issue by tpoisonooo** [flame/how-to-optimize-gemm#13]
In [Optimization_4x4_10](https://github.com/flame/how-to-optimize-gemm/wiki/Optimization_4x4_10) ,
I think `OLD` should be `MMult_1x4_9`, not `MMult_4x4_9`.

**Comment by jianyuh** [comment]
Should still be ```MMult_4x4_9```. Somehow the order on the right sidebar at Github is not correct. ```MMult_4x4_9``` is shown at the bottom.

**Comment by tpoisonooo** [comment]
Indeed.

Since so few people are used to ColMajor Matrix, I have implemented [ARM RowMajor sgemm](https://github.com/tpoisonooo/how-to-optimize-gemm).

**Comment by jianyuh** [comment]
Wow! Your work is amazing! Look forward to its final document!
