### ISSUE TITLE
Optimization_1x4_6

### ISSUE THREAD

**Issue by xingjinglu** [flame/how-to-optimize-gemm#5]
In this optimization, it replace C(0, 1), ... , and C(0, 3) with register variable, I think if this step have benefits, it comes from two reasons:
1) avoid redundant computing index of C(0, x) and A(0, p);
2) Have more chances in utilizing data-reuse for C(0, x)；
3） it may come from the use of register variable.

Instead, I replace these variables with ordinary float/double c_00, c_01, ..., c_03, the result show we get more benefits.

So, I guess whether to use register variable is not the key optimization.

**Comment by SudoNohup** [comment]
The optimization in this guide was done on Intel Nehalem/Westmere architecture when this guide was developed at around 2008~2010. Back then the Intel/GNU compiler was not that advanced. Now the compiler can lift some variables in registers automatically. I would suggest adding "-O0" compiler flag in your code to observe the performance difference. The key point for this step is to understand that keeping the variables in the registers can help reach high performance.
