### ISSUE TITLE
how do you calculate the gflops ?

### ISSUE THREAD

**Issue by victorygogogo** [flame/how-to-optimize-gemm#6]
how do you calculate the gflops ?

for example , you have 2 matrix A and B ,A.shape is 3X4  B.shape is 4X3, so the result is 3X3 ,the cost time is about 0.001ms, flops = 3X4x2/0.0001ms ?

**Comment by SudoNohup** [comment]
If the matrix sizes of A, B, C are mxk, kxn, mxn, separately, for matrix multiplication, then the GFLOPS = 2 x m x k x n / time * 10^(-9) (the total number of floating point operations divided by the running time in seconds, and G means Giga, or 10 ^ 9).
In your case, gflops = 2 x 3 x 4 x 3 / (0.001 * 10^(-3))  * 10(-9) = 0.072  (here 10 ^(-3) is translating ms to s)
