### ISSUE TITLE
if the matrix's width and height %4 is not zero ,how to optimize it ?

### ISSUE THREAD

**Issue by victorygogogo** [flame/how-to-optimize-gemm#7]
if the matrix's width and height %4 is not zero ,how to optimize it ?

I do not see the optimize way about this ?

can you share it ?

**Comment by xzy256** [comment]
@victorygogogo could you understand it?  I have same confusion too.

**Comment by SudoNohup** [comment]
You can pad zeros or peel the fringes. For the final optimized version with packing routines, you can just allocate the packing buffers with the dimension to be multiple of 4, and pad the leftover entries with zeros.

**Comment by xzy256** [comment]
Thank you for your  idea. It sounds great! By the way, i have a other way. I use `%` for getting remainder，then use three `for loops` to deel with the remainder.

**Comment by SudoNohup** [comment]
Sounds reasonable!
