### ISSUE TITLE
Markup

### ISSUE THREAD

**Issue by amitdo** [flame/how-to-optimize-gemm#9]
https://github.com/flame/how-to-optimize-gemm#related-links

 *   [BLISlab: A Sandbox for Optimizing GEMM] (https://github.com/flame/blislab)
 *   [GEMM: From Pure C to SSE Optimized Micro Kernels] (http://apfel.mathematik.uni-ulm.de/~lehn/sghpc/gemm/)

You need to remove the space between `[Text]` to `(url)`.

 *   [BLISlab: A Sandbox for Optimizing GEMM](https://github.com/flame/blislab)
 *   [GEMM: From Pure C to SSE Optimized Micro Kernels](http://apfel.mathematik.uni-ulm.de/~lehn/sghpc/gemm/)

**Comment by SudoNohup** [comment]
Fixed. Thanks!
